package com.lsy.pojo;

// Generated 2017-12-24 11:09:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MEmployees generated by hbm2java
 */
public class MEmployees implements java.io.Serializable {

    private Integer employeeId;

    private String name;

    private String sex;

    private String age;

    private String birthday;

    private String department;

    private String duty;

    private String education;

    private String school;

    private String address;

    private String mobile;

    private String telephone;

    private boolean married;

    private String birthPlace;

    private boolean dimission;

    private boolean deleted;

    private boolean holiday;

    private Set<Users> userses = new HashSet<Users>(0);

    public MEmployees() {
    }

    public MEmployees(String name, String sex, String birthday,
            String department, String duty, String education, String school,
            String address, String mobile, String telephone, boolean married,
            String birthPlace, boolean dimission, boolean deleted,
            boolean holiday) {
        this.name = name;
        this.sex = sex;
        this.birthday = birthday;
        this.department = department;
        this.duty = duty;
        this.education = education;
        this.school = school;
        this.address = address;
        this.mobile = mobile;
        this.telephone = telephone;
        this.married = married;
        this.birthPlace = birthPlace;
        this.dimission = dimission;
        this.deleted = deleted;
        this.holiday = holiday;
    }

    public MEmployees(String name, String sex, String age, String birthday,
            String department, String duty, String education, String school,
            String address, String mobile, String telephone, boolean married,
            String birthPlace, boolean dimission, boolean deleted,
            boolean holiday, Set<Users> userses) {
        this.name = name;
        this.sex = sex;
        this.age = age;
        this.birthday = birthday;
        this.department = department;
        this.duty = duty;
        this.education = education;
        this.school = school;
        this.address = address;
        this.mobile = mobile;
        this.telephone = telephone;
        this.married = married;
        this.birthPlace = birthPlace;
        this.dimission = dimission;
        this.deleted = deleted;
        this.holiday = holiday;
        this.userses = userses;
    }

    public Integer getEmployeeId() {
        return this.employeeId;
    }

    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getAge() {
        return this.age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getBirthday() {
        return this.birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getDepartment() {
        return this.department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public String getDuty() {
        return this.duty;
    }

    public void setDuty(String duty) {
        this.duty = duty;
    }

    public String getEducation() {
        return this.education;
    }

    public void setEducation(String education) {
        this.education = education;
    }

    public String getSchool() {
        return this.school;
    }

    public void setSchool(String school) {
        this.school = school;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public boolean isMarried() {
        return this.married;
    }

    public void setMarried(boolean married) {
        this.married = married;
    }

    public String getBirthPlace() {
        return this.birthPlace;
    }

    public void setBirthPlace(String birthPlace) {
        this.birthPlace = birthPlace;
    }

    public boolean isDimission() {
        return this.dimission;
    }

    public void setDimission(boolean dimission) {
        this.dimission = dimission;
    }

    public boolean isDeleted() {
        return this.deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public boolean isHoliday() {
        return this.holiday;
    }

    public void setHoliday(boolean holiday) {
        this.holiday = holiday;
    }

    public Set<Users> getUserses() {
        return this.userses;
    }

    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }

}
