package com.lsy.pojo;

// Generated 2017-12-24 11:09:20 by Hibernate Tools 3.4.0.CR1

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

    private String username;

    private MEmployees MEmployees;

    private String password;

    private boolean enabled;

    private boolean deleted;

    public Users() {
    }

    public Users(String username, MEmployees MEmployees, String password,
            boolean enabled, boolean deleted) {
        this.username = username;
        this.MEmployees = MEmployees;
        this.password = password;
        this.enabled = enabled;
        this.deleted = deleted;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public MEmployees getMEmployees() {
        return this.MEmployees;
    }

    public void setMEmployees(MEmployees MEmployees) {
        this.MEmployees = MEmployees;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isEnabled() {
        return this.enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public boolean isDeleted() {
        return this.deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

}
